version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: >
      bash -c "poetry run uvicorn app:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped